# Generated by Django 3.2.12 on 2026-06-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloAssoImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='form_items', max_length=50)),
                ('organization_slug', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=50)),
                ('form_slug', models.CharField(max_length=255)),
                ('with_details', models.BooleanField(default=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='HelloAssoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helloasso_id', models.CharField(max_length=120)),
                ('organization_slug', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=50)),
                ('form_slug', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('raw_item', models.JSONField()),
                ('latest_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_items', to='api.helloassoimport')),
            ],
            options={
                'ordering': ('-last_synced_at',),
            },
        ),
        migrations.AddIndex(
            model_name='helloassoitem',
            index=models.Index(fields=['organization_slug', 'form_type', 'form_slug'], name='api_helloas_organiz_8e1606_idx'),
        ),
        migrations.AddIndex(
            model_name='helloassoitem',
            index=models.Index(fields=['payer_email'], name='api_helloas_payer_e_7cd8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='helloassoitem',
            index=models.Index(fields=['status'], name='api_helloas_status_ab003b_idx'),
        ),
        migrations.AddConstraint(
            model_name='helloassoitem',
            constraint=models.UniqueConstraint(fields=('helloasso_id', 'organization_slug', 'form_type', 'form_slug'), name='uniq_helloasso_item_per_form'),
        ),
    ]
