# Generated by Django 3.2.12 on 2026-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_helloasso_campaign_member_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='helloasso_form_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
