# Generated by Django 3.2.12 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaign_helloasso_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_merge',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
