# Generated by Django 3.2.12 on 2026-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260612_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
