# Generated by Django 3.2.12 on 2026-06-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_campaign_last_manual_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfckExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='licences_excel', max_length=50)),
                ('structure_id', models.PositiveIntegerField(blank=True, null=True)),
                ('structure_select_path', models.CharField(blank=True, default='', max_length=255)),
                ('export_path', models.CharField(max_length=255)),
                ('export_method', models.CharField(default='POST', max_length=10)),
                ('export_payload', models.JSONField(blank=True, default=dict)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_blob', models.BinaryField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ffck_exports', to='api.campaign')),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='FfckExportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('licence', models.CharField(blank=True, default='', max_length=100)),
                ('nom', models.CharField(blank=True, default='', max_length=255)),
                ('categorie', models.CharField(blank=True, default='', max_length=120)),
                ('certificat', models.CharField(blank=True, default='', max_length=500)),
                ('autorisation_parentale', models.CharField(blank=True, default='', max_length=500)),
                ('statut', models.CharField(blank=True, default='', max_length=50)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ffck_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.ffckexport')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ffck_export_rows', to='api.member')),
            ],
            options={
                'ordering': ('row_index', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='ffckexportrow',
            index=models.Index(fields=['ffck_export', 'statut'], name='api_ffckexp_ffck_ex_7e1df9_idx'),
        ),
        migrations.AddIndex(
            model_name='ffckexportrow',
            index=models.Index(fields=['licence'], name='api_ffckexp_licence_343326_idx'),
        ),
        migrations.AddIndex(
            model_name='ffckexportrow',
            index=models.Index(fields=['nom'], name='api_ffckexp_nom_331b0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ffckexportrow',
            constraint=models.UniqueConstraint(fields=('ffck_export', 'row_index'), name='uniq_ffck_export_row_index'),
        ),
        migrations.AddIndex(
            model_name='ffckexport',
            index=models.Index(fields=['campaign', '-fetched_at'], name='api_ffckexp_campaig_ffaf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ffckexport',
            index=models.Index(fields=['structure_id'], name='api_ffckexp_structu_63de99_idx'),
        ),
    ]
