# Generated by Django 3.2.12 on 2026-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20260612_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ffck_certificat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='ffck_certificat_expiration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='ffck_licence_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
