# Generated by Django 3.2.12 on 2026-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20260613_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='helloasso_form_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
