# Generated by Django 3.2.12 on 2026-06-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_member_helloasso_form_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="badge_ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="badge_owned",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BadgeImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(default="badge_excel", max_length=50)),
                ("rows_count", models.PositiveIntegerField(default=0)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("file_blob", models.BinaryField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="badge_imports",
                        to="api.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ("-fetched_at",),
            },
        ),
        migrations.CreateModel(
            name="BadgeImportRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_index", models.PositiveIntegerField()),
                ("licence", models.CharField(blank=True, default="", max_length=100)),
                ("first_name", models.CharField(blank=True, default="", max_length=150)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("badge_owned", models.BooleanField(default=False)),
                ("badge_ordered", models.BooleanField(default=False)),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="api.badgeimport",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badge_import_rows",
                        to="api.member",
                    ),
                ),
            ],
            options={
                "ordering": ("row_index", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="badgeimportrow",
            constraint=models.UniqueConstraint(
                fields=("badge_import", "row_index"), name="uniq_badge_import_row_index"
            ),
        ),
        migrations.AddIndex(
            model_name="badgeimport",
            index=models.Index(
                fields=["campaign", "-fetched_at"], name="api_badgeim_campaig_41dc19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badgeimportrow",
            index=models.Index(fields=["licence"], name="api_badgeim_licence_1af4f0_idx"),
        ),
        migrations.AddIndex(
            model_name="badgeimportrow",
            index=models.Index(fields=["name", "first_name"], name="api_badgeim_name_17b28c_idx"),
        ),
    ]
