# Generated by Django 3.2.12 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_encrypt_all_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeimport",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="badgeimportrow",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
