# Generated by Django 6.0.6 on 2026-06-15 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_member_certificat_file_fields"),
    ]

    operations = []
