# Generated by Django 3.2.12 on 2026-07-31

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_userlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ffckexportrow",
            name="photo",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=api.models.ffck_photo_upload_to,
            ),
        ),
    ]
