# Generated by Django 3.2.12 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_ffckexportrow_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ffckexportrow",
            name="photo_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
