# Generated by Django 3.2.12 on 2026-07-31

from django.db import migrations


def remove_legacy_photo_ffck_columns(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE api_member
            DROP COLUMN IF EXISTS photo_ffck,
            DROP COLUMN IF EXISTS photo_ffck_content_type,
            DROP COLUMN IF EXISTS photo_ffck_size;
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_ffckexportrow_photo_original_name"),
    ]

    operations = [
        migrations.RunPython(remove_legacy_photo_ffck_columns, migrations.RunPython.noop),
    ]
