# Generated by Django 6.0.6 on 2026-07-31

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_remove_legacy_member_photo_ffck_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelloAssoAuthorizationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_key", models.CharField(max_length=64, unique=True)),
                (
                    "access_token",
                    django_cryptography.fields.encrypt(models.TextField(blank=True, default="")),
                ),
                (
                    "refresh_token",
                    django_cryptography.fields.encrypt(models.TextField(blank=True, default="")),
                ),
                ("access_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization_slug",
                    django_cryptography.fields.encrypt(
                        models.CharField(blank=True, default="", max_length=255)
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
