# Generated by Django 6.0.6 on 2026-07-31

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_helloasso_authorization_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelloAssoAuthorizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_id", models.CharField(max_length=64, unique=True)),
                ("code_verifier", django_cryptography.fields.encrypt(models.TextField())),
                ("status", models.CharField(default="pending", max_length=16)),
                (
                    "error",
                    django_cryptography.fields.encrypt(models.TextField(blank=True, default="")),
                ),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
